export const eventos = [
  {
    id: 1,
    name: "Virgilio Madinah",
    date: "2024-07-21T19:00:00Z",
    brand: "Bridal Runaway Latam",
    collection: "VIRGILIOMADINAH Novias Primavera / Verano 2025",
  },
  {
    id: 6,
    name: "WMF Demo 2024",
    date: "2024-11-21T19:00:00Z",
    brand: "WMF",
  },
  // {
  //   eventId: 3,
  //   eventName: "Winter Wonderland Runway",
  //   eventDate: "10/12/2024",
  //   eventBrand: "Gucci",
  // },
  // {
  //   eventId: 4,
  //   eventName: "Summer Extravaganza",
  //   eventDate: "25/06/2024",
  //   eventBrand: "Versace",
  // },
  // {
  //   eventId: 5,
  //   eventName: "Classic Couture Showcase",
  //   eventDate: "30/01/2024",
  //   eventBrand: "Prada",
  // },
  // {
  //   eventId: 6,
  //   eventName: "Haute Couture Gala",
  //   eventDate: "15/05/2024",
  //   eventBrand: "Valentino",
  // },
  // {
  //   eventId: 7,
  //   eventName: "Elegant Evening Wear",
  //   eventDate: "12/11/2024",
  //   eventBrand: "Armani",
  // },
  // {
  //   eventId: 8,
  //   eventName: "Spring/Summer Fashion Week",
  //   eventDate: "05/04/2024",
  //   eventBrand: "Louis Vuitton",
  // },
  // {
  //   eventId: 9,
  //   eventName: "Resort Collection Preview",
  //   eventDate: "19/07/2024",
  //   eventBrand: "Balenciaga",
  // },
  // {
  //   eventId: 10,
  //   eventName: "Midnight Glamour Show",
  //   eventDate: "28/10/2024",
  //   eventBrand: "Givenchy",
  // },
  // {
  //   eventId: 11,
  //   eventName: "Luxe Lifestyle Presentation",
  //   eventDate: "08/02/2024",
  //   eventBrand: "Hermès",
  // },
  // {
  //   eventId: 12,
  //   eventName: "Red Carpet Collection",
  //   eventDate: "03/03/2024",
  //   eventBrand: "Oscar de la Renta",
  // },
];
