import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "./globals.css";
import ScrollToTopFab from "@_shared/components/ScrollToTop/ScrollToTop";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <body className="flex flex-col justify-around p-16">
          {children}
          <ScrollToTopFab />
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
