import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import "../globals.css";
import ScrollToTopFab from "@_shared/components/ScrollToTop/ScrollToTop";
import Image from "next/image";

import logo from "../../../public/WMF.svg";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AppRouterCacheProvider>
        <body className="flex flex-col justify-around p-16 min-h-screen">
          <Image
            src={logo}
            width={100}
            height={50}
            alt={"We Move Fashion nav logo"}
            className="absolute top-16 right-16"
          />
          {children}
          <ScrollToTopFab />
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
